// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBecn5qykdjdZNsBtlc6pEY36WVw9DYkAs',
    appId: '1:189922228443:web:405cc3e6e9da6f961934fe',
    messagingSenderId: '189922228443',
    projectId: 'flutter-chat-app-30683',
    authDomain: 'flutter-chat-app-30683.firebaseapp.com',
    storageBucket: 'flutter-chat-app-30683.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALVqDFYi6d_cW61cJw3eyqwrMwMSym89g',
    appId: '1:189922228443:android:4bfed22299a5ca931934fe',
    messagingSenderId: '189922228443',
    projectId: 'flutter-chat-app-30683',
    storageBucket: 'flutter-chat-app-30683.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7eZI1bwZhkH7PmrI2K6uPIap97aso-Bs',
    appId: '1:189922228443:ios:136c8ce63ad9aec21934fe',
    messagingSenderId: '189922228443',
    projectId: 'flutter-chat-app-30683',
    storageBucket: 'flutter-chat-app-30683.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7eZI1bwZhkH7PmrI2K6uPIap97aso-Bs',
    appId: '1:189922228443:ios:136c8ce63ad9aec21934fe',
    messagingSenderId: '189922228443',
    projectId: 'flutter-chat-app-30683',
    storageBucket: 'flutter-chat-app-30683.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBecn5qykdjdZNsBtlc6pEY36WVw9DYkAs',
    appId: '1:189922228443:web:234d11581370ad5d1934fe',
    messagingSenderId: '189922228443',
    projectId: 'flutter-chat-app-30683',
    authDomain: 'flutter-chat-app-30683.firebaseapp.com',
    storageBucket: 'flutter-chat-app-30683.firebasestorage.app',
  );
}